#!/usr/bin/env bash
set -ex

curl -L "https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer" -o /builds/worker/pyenv-installer
chmod +x /builds/worker/pyenv-installer
/builds/worker/pyenv-installer
rm /builds/worker/pyenv-installer
cat << EOF >> /builds/worker/.bashrc
eval "\$(pyenv init --path)"
eval "\$(pyenv init -)"
eval "\$(pyenv virtualenv-init -)"
EOF
source /builds/worker/.bashrc

# Log some debugging info
pyenv --version
git -C "$(pyenv root)" rev-parse HEAD

for i in ${1//,/ }
do
    version=$(pyenv latest --known $i)
    pyenv install $version
done
chmod 777 /builds/worker/.pyenv/shims
pyenv rehash
