---
trust-domain: "{{cookiecutter.trust_domain}}"
task-priority: low

taskgraph:
  cached-task-prefix: "{{cookiecutter.trust_domain}}.v2.{{cookiecutter.trust_project}}"
  repositories:
    {{cookiecutter.__package_name}}:
      name: "{{cookiecutter.project_name}}"

workers:
  aliases:
    images:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    linux:
      provisioner: '{trust-domain}-t'
      implementation: docker-worker
      os: linux
      worker-type: 't-{alias}-large-gcp'
